### ISSUE TITLE
Question: CSGO skins

### ISSUE THREAD

**Issue by thevangelist** [Mishcatt/VTF-Editor#9]
Could you help me to use this for CSGO weapon skins?

I found out that windows users use a VTFedit editor, but I am unable to get it working on mac (found some version, but it doesnt open at all).

Here's the VTF file settings used in one video for TGA > VTF conversion for CSGO weapon skins.

![Screen Shot 2019-09-18 at 10 27 11 PM](https://user-images.githubusercontent.com/3482617/65179732-0b23ef80-da64-11e9-8f4e-e7cd6a6caefa.png)

The .tga file is 2048 x 2048. I tried a conversion with the current VTF-editor version online, but it doesn't display correctly on the CSGO workbench.

Check these out for more references

Docs: http://counter-strike.net/workshop/workshopfaq#weapons
Tutorial: https://www.youtube.com/watch?v=hv6p_12W0rY

**Comment by thevangelist** [comment]
I can help you in return with styling / branding the tool!

**Comment by thevangelist** [comment]
Googled around more, might be the case of this: https://github.com/ValveSoftware/csgo-osx-linux/issues/253, why my texture is all black..

**Comment by Mishcatt** [comment]
> Googled around more, might be the case of this: [ValveSoftware/csgo-osx-linux#253](https://github.com/ValveSoftware/csgo-osx-linux/issues/253), why my texture is all black..

Hi, i'm sorry to hear that a different issue holds you back. The current project was specifically made to create sprays in Team Fortress 2 and possibly outputs slightly out-of-spec (dummy header) files, that some tools may not like, but so far seem to be compatible. I can't help you unfortunately as i have less and less time for this project. Good luck.
